---
title: "hw4"
format: pdf
pdf-engine: xelatex
mainfont: Times
editor: visual
---

## 1

### a

$W, Y$

### b

$X, W, Y$

### c

$Y, Z$

### d

$Y, Z, T$

### e

- $X-Y-T$
- $X-Y-Z-T$
- $X-Y-W-Z-T$
- $X-W-Y-T$
- $X-W-Y-Z-T$
- $X-W-Z-T$
- $X-W-Z-Y-T$

### f

- $X-Y-T$
- $X-Y-Z-T$
- $X-W-Y-T$
- $X-W-Y-Z-T$
- $X-W-Z-T$

## 2

### a

\begin{tikzpicture}
  \node (x) {$X$};
  \node (ux) [above of=x] {$U_X$};
  \node (y) [below left of=x] {$Y$};
  \node (uy) [above of=y] {$U_Y$};
  \node (z) [below right of=x] {$Z$};
  \node (uz) [above of=z] {$U_Z$};
  
  \draw[->] (x) -- (y);
  \draw[->] (y) -- (z);
  \draw[dashed, ->] (uz) -- (z);
  \draw[dashed, ->] (ux) -- (x);
  \draw[dashed, ->] (uy) -- (y);
\end{tikzpicture}


### b

$$
\begin{aligned}
E[Z | Y = 3] = \sum_{z}zP(Z = z| Y = 3) = 0 \ + \ ... \ + \ 0 + \frac{3}{16}\cdot 1 + 0 + \ ... \ + 0 = \frac{3}{16}
\end{aligned}
$$

### c

$$
E[Z | X = 3] = \sum_zzP(Z = z | X = 3) = \frac{1}{16}
$$

### d

We apply the Markov condition here:

$$
E[Z | X = 1, Y = 3] = \sum_zzP(Z  = z| X = 1, Y = 3) = \sum_zzP(Z = z | Y = 3) = \frac{3}{16}
$$


## 3

### a

- $\{X, Z_2\}$ are d-separated by $\{Z_3, Z_1\}$
- $\{X, Y\}$ are d-separated by $\{W, Z_2, Z_3\}$
- $\{Z_1, W\}$ are d-separated by $\{X\}$
- $\{Z_1, Z_2\}$ are d-separated by $\{\}$
- $\{Z_1, Y\}$ are d-separated by $\{W, Z_3, Z_2\}$
- $\{Z_3, W\}$ are d-separated by $\{X\}$
- $\{Z_2, W\}$ are d-separated by $\{X\}$

### b

- $\{W, Z_3\}$ are d-separated by $\{X\}$
- $\{W, Z_1\}$ are d-separated by $\{X\}$

### c

I don't think it would hurt the quality of our prediction since it is essentially double blocking a backdoor path that would already get blocked by not conditioning on $Y$. It certainly *would* help, if we were conditioning on $Y$ though.

## 4

### a

Needs Z and then any combination of $A, B, C, D$

- $\{Z, D\}$, $\{Z, C\}$, $\{Z, B\}$, $\{Z, A\}$
- $\{Z, D, C\}$, $\{Z, D, B\}$, $\{Z, D, A\}$, $\{Z, C, A\}$, $\{Z, B, A\}$, $\{Z, B, C\}$
- $\{X, D, C, B\}$, $\{Z, D, C, A\}$, $\{Z, D, B, A\}$, $\{Z, B, C, A\}$
- $\{Z, D, C, B, A\}$

The minimal ones are 

- $\{Z, D\}$, $\{Z, C\}$, $\{Z, B\}$, $\{Z, A\}$, $\{Z, X\}$, $\{Z, W\}$

### b

The sets can be described as follows:

One option is to include only $c$. Otherwise, the set 

- must include Z or C or both. If it does not include $C$ it must also have
- any combination of $B, A, X, W$

The minimal sets are $\{C\}$, $\{Z, A\}$, $\{Z, B\}$


## 5

### a

$$
P(X, Y, Z) = P(X|Z)P(Y | X, Z)P(Z)
$$

### b

\begin{tikzpicture}
  \node (z) {$Z$};
  \node (y) [below right of=z] {$Y$};
  \node (x) [below left of=z] {$X = x$};
  
  \draw[->] (x) -- (y);
  \draw[->] (z) -- (y);
\end{tikzpicture}

### c

$$
\begin{aligned}
P(Y, Z \ | \ \text{do}(X=x)) &= P_m(Z)P_m(X = x|Z)P_m(Y | X = x, Z) \\
&= P(Z)P(Y|X = x, Z)
\end{aligned}
$$

$$
\begin{aligned}
P(Y \ | \ \text{do}(X = x)) &= \sum_zP(Y, Z = z \ | \ \text{do}(X = x)) \\
&= \sum_zP(Z = z)P(Y | X = x, Z = z)
\end{aligned}
$$

### d

$$
P(X, Y, Z) = P(X)P(Y | X)P(Z |X,Y)
$$


### e

\begin{tikzpicture}
  \node (z) {$Z$};
  \node (y) [below right of=z] {$Y$};
  \node (x) [below left of=z] {$X = x$};
  
  \draw[->] (x) -- (z);
  \draw[->] (x) -- (y);
  \draw[->] (y) -- (z);
\end{tikzpicture}

### f

$$
\begin{aligned}
P(Y, Z \ | \ \text{do}(X = x)) &= P_m(X = x)P_m(Y | X = x)P_m(Z | X=x, Y) \\
&= P(Y|X = x)P(Z|X = x, Y)
\end{aligned}
$$

$$
\begin{aligned}
P(Y \ | \ \text{do}(X = x)) &= \sum_zP(Y, Z \ | \ \text{do}(X = x)) \\
&= \sum_zP(Y|X = x)P(Z = z|X = x, Y) \\
&=P(Y|X =x)\sum_zP(Z=z|X = x, Y) \\
&= P(Y | X = x)\cdot 1 
\end{aligned}
$$

### g

No (as we'd expect)

### h

For common cause $\{Z\}$ satisfies the backdoor criterion and so we use tha adjustment formula to get

$$
P(Y \ | \ \text{do}(X = x)) = \sum_zP(Y | X = x, Z= z)P(Z = z)
$$

which is exactly what we got in part (c)


For collider there are no backdoor paths into $X$. Thus we simply have

$$
P(Y \ | \ \text{do}(X = x))  = P(Y | X = x)
$$

which again is what we got previously.

## 6

Suppose we are trying to estimate the effect of Daniel's jokes on how well the 394 students understand the material

- $D$: Daniel's jokes
- $Y$: 394 students understand the material
- $X_1$: Friendship with Daniel
- $X_2$: How well Daniel is feeling 

Friendship with Daniel affects how well Daniel is feeling, which in turn affects what Daniel's jokes are like. What's more, since Daniel is a genius, friendship with him results in a greater understanding of the material. Unfortunately we often don't know the true inner feelings of Daniel, but in this case where we simply care about estimating a causal effect, we don't have to worry about the fact that this variable is unobserved.


\begin{tikzpicture}
  \node (D) {$D$};
  \node (Y) [right of=D] {$Y$};
  \node (X1) [above of=Y]{$X_1$};
  \node (X2) [above of=D] {$X_2$};
  \draw[->] (D) -- (Y);
  \draw[->] (X1) -- (Y);
  \draw[dashed, ->] (X1) -- (X2);
  \draw[dashed, ->] (X2) -- (D);
\end{tikzpicture}

I don't really think that this setting is very plausible in reality. In trying to think of an example I felt like most of the time a utilization of the backdoor criterion is only possible when we observe variables that we would not realistically observe. It's only in these fairly fabricated examples where we observe exactly the variables we need to observe in order to satisfy the backdoor criterion.